---
# tasks file for prometheus

- name: Disable firewalld
  become: yes
  systemd:
    name: firewalld
    state: stopped
  when: ansible_os_family == "RedHat"

- name: Create user 
  become: yes
  user:
    name: "{{ prometheus_user }}"
    shell: /bin/false
    createhome: "{{ create_home }}"
    state: present

- name: Create folder
  become: yes
  file:
    path: "{{ path_node_exporter }}"
    state: directory
    owner: "{{ prometheus_user }}"
    mode: 440
 
- name: Get node exporter
  become: yes
  unarchive:
    src: "{{ download_node_exporter }}"
    dest: "{{ path_node_exporter }}"
    owner: "{{ prometheus_user }}"
    remote_src: yes

- name: Create service
  become: yes
  template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    owner: "{{ prometheus_user }}"

- name: Start service
  become: yes
  systemd:
    name: node_exporter.service
    enabled: yes
    state: started
    daemon_reload: yes
